services:
  next:
    image: node:22-slim
    working_dir: /app/nss-labeler
    entrypoint: npm run dev
    environment:
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - "./next:/app"
    ports:
      - "${NEXT_PORT}:3000"
    user: "1000"
